[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "drC1Ron"
authors = [{name = "drC1Ron", email = "drC1Ron@ie.com"}]
dynamic = ["version", "description"]
